#!/bin/sh

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# xsetroot -solid grey
xsetroot -mod 5 12 -fg "#006064" -bg "#B0BEC5"
vncconfig -iconic &

gnome-panel &
gnome-settings-daemon &
metacity &
nautilus
